version: '3.6'
services:
  postgres:
    image: postgres:16-bookworm
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:?Set DB_PASSWORD in .env}
      - POSTGRES_USER=${DB_USERNAME:?Set DB_USERNAME in .env}
      - POSTGRES_DB=${DB_NAME:-app}
  rabbitmq:
    image: rabbitmq:3.12.12-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:?Set RABBITMQ_USERNAME in .env}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:?Set RABBITMQ_PASSWORD in .env}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/apps/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/apps/rabbitmq/log/:/var/log/rabbitmq
  backend:
    build: .
    environment:
      DB_URL: ${DB_URL:?Set DB_URL in .env}
      DB_USERNAME: ${DB_USERNAME:?Set DB_USERNAME in .env}
      DB_PASSWORD: ${DB_PASSWORD:?Set DB_PASSWORD in .env}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:?Set RABBITMQ_USERNAME in .env}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:?Set RABBITMQ_PASSWORD in .env}
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY:?Set JWT_SIGNING_KEY in .env}
    ports:
      - "8080:8080"
